services:
  postgressql:
    image: postgres:${POSTGRES_VERSION}
    container_name: lg-infra-db-postgres
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${POSTGRES_MEM_LIMIT}
volumes:
  db:
    driver: local