version: "3"

services:
  sonarqube:
    image: sonarqube:${SONAR_VERSION}
    container_name: sonar_qube
    expose:
      - ${SONAR_PORT}
    ports:
      - "127.0.0.1:${SONAR_PORT}:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=${POSTGRESQL_USER}
      - sonar.jdbc.password=${POSTGRESQL_PASSWORD}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: db_sonar
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
