filebeat.inputs:
  - type: log
    id: default-filestream
    paths:
      - ingest_data/*.log
    enabled: true
    json.keys_under_root: true

    processors:
      - decode_json_fields:
          fields: [ 'message_filter' ]
          target: json

output.logstash:
  hosts: [ "${HOSTS}" ]
