filebeat.inputs:
  - type: filestream
    enabled: true
    id: default-filestream
    paths:
      - ingest_data/*.log
    take_over:
      enabled: true
    json.keys_under_root: true

    processors:
      - decode_json_fields:
          fields: [ 'message' ]
          target: json

output.logstash:
  hosts: [ "${HOSTS}" ]
